version: 2.1

#orbs:
#  android: circleci/android@0.2.1

jobs:
  build:
    working_directory: ~/code
    #executor: android/android
    docker:
      - image: circleci/android:api-29
        auth:
          username: arsenyzp
          password: $DOCKERHUB_PASSWORD
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          command: ./gradlew build
      - attach_workspace:
          at: ./artifacts
      - run:
          filters:
            #            branches:
            #              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/
          name: Initial build
          command: ./gradlew clean assembleRelease --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: artifacts/
      - publish-github-release


publish-github-release:
  docker:
    - image: cibuilds/github:0.10
  steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        filters:
          #          branches:
          #            only: master
          tags:
            only: /^\d+\.\d+\.\d+$/
        name: "Publish Release on GitHub"
        command: |
          VERSION=$CIRCLE_TAG
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
